export const urlHomeRoute=()=>'/';
export const urlRequestOrderRoute=()=>'/order';
export const urlReviewRoute=()=>'/review';
export const urlCarrerRoute=()=>'/carrer';
export const urlGalleryRoute=()=>'/gallery';
export const urlAboutRoute=()=>'/about';
export const urlContactRoute=()=>'/contact';
export const urlReturnPolicy=()=>'/return';
export const urlTermsConditionRoute=()=>'/termsCondition';
export const urlPrivacyPolicy=()=>'/privacy';
export const urlProductDetails=()=>'/product/details/'